const DERSLER = [
    "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ - SÜMEYYE ULU",
    "TARİH - FERHAN DURGUN",
    "FİZİK - NURCAN KÖSEOĞLU",
    "MATEMATİK - HÜLYA AKYAZI DEMİRDAĞ",
    "MESLEKİ GELİŞİM - FİSUN ELMAS",
    "İNGİLİZCE - PINAR KARACAR",
    "COĞRAFYA - HÜSAMETTİN ERTÜRK",
    "MATEMATİK - MİNE KAYA SEL",
    "KİMYA - NERGİZ ERDİM",
    "MESLEKİ GELİŞİM - BEYZA NUR KOÇAK",
    "TARİH - HALİL HATİPOĞLU",
    "MESLEKİ GELİŞİM - ERDEM TEMEL",
    "İNGİLİZCE - MİRAY GÜNEY",
    "TÜRK DİLİ VE EDEBİYATI - TUĞÇE GÜVEN",
    "MESLEKİ GELİŞİM - MÜŞRA SEVİNÇ",
    "MATEMATİK - KUBİLAY ORHAN GÜNATA",
    "TÜRK DİLİ VE EDEBİYATI - MACİDE MELTEM DOĞRAMACI",
    "TÜRK DİLİ VE EDEBİYATI - KEVSER DUR",
    "SERVİS HAZIRLIKLARI - LALE ÖLMEZ",
    "FELSEFE - ZAKİR ÜNGÖR",
    "MESLEKİ İNGİLİZCE - MİRAY GÜNEY",
    "TARİH - BEDRİ GÜLSEN",
    "BİYOLOJİ - ERDOĞAN AVCI",
    "GIDA MİKROBİYOLOJİSİ - MERVE GEÇER",
    "GIDA KİMYASI - BEYZA NUR KOÇAK",
    "TEMEL YİYECEK ÜRETİMİ - LALE ÖLMEZ",
    "YEMEK GRUPLARININ SERVİSİ - ESRA ÇAYDAŞ ATİK",
    "BESLENME - BEYZA NUR KOÇAK",
    "ÖZEL GIDALAR - BEYZA NUR KOÇAK",
    "GIDA ÜRETİM TEKNOLOJİLERİ - BEYZA NUR KOÇAK",
    "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ - FERHAN DURGUN",
    "DİN KÜLTÜRÜ VE AHLAK BİLGİSİ - HALİL HATİPOĞLU",
    "TÜRK DÜNYASI TARİHİ - HALİL HATİPOĞLU"
]

const ogretmenler = [];
DERSLER.forEach((v,i)=>{
  ogretmenler.push({id:i+1,isim:v})
})
